### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT

### ISSUE THREAD

**Issue by nayouzhenai** [gejun123456/MyBatisCodeHelper-Pro#1000]
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2024.1.2` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.2.9`

### Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.ccnode.codegenerator.ae.r.i' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.ccnode.codegenerator.MyBatisCodeHelperPro]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by gejun123456** [comment]
升级下插件

**Comment by niejunzhi** [comment]
IDEA 2024.2.4报错
![微信截图_20241109213336](https://github.com/user-attachments/assets/d6d1546d-9ce9-4901-ac3e-4aaf1b419c84)

**Comment by gejun123456** [comment]
> IDEA 2024.2.4报错 ![微信截图_20241109213336](https://private-user-images.githubusercontent.com/117997664/384609354-d6d1546d-9ce9-4901-ac3e-4aaf1b419c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDM4NDMsIm5iZiI6MTczMTIwMzU0MywicGF0aCI6Ii8xMTc5OTc2NjQvMzg0NjA5MzU0LWQ2ZDE1NDZkLTljZTktNDkwMS1hYzNlLTRhYWYxYjQxOWM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjNmNjRmNTQyMzdlMzFhYzFiYWNjYTQ3NTI4MmI0MWU3ODkyODAzMzY5ZmRmZDMwZjU5ZGVhMTI5MjliYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ybhMVRjWY171R_X_atc5ZYmcSNKMuF4azA9jxWs5HW0)

这个不是我的插件，看他有没有升级版本啥的
