### ISSUE TITLE
IDEA15.0.6不知道为什么有个错误

### ISSUE THREAD

**Issue by wzyjobs** [gejun123456/MyBatisCodeHelper-Pro#106]
```org/jetbrains/uast/UastUtils
java.lang.NoClassDefFoundError: org/jetbrains/uast/UastUtils
	at com.ccnode.codegenerator.view.MybatisJavaLineMarkerProvider.collectNavigationMarkers(MybatisJavaLineMarkerProvider.kt:25)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:39)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



java.lang.NoClassDefFoundError: org/jetbrains/uast/UastUtils
	at com.ccnode.codegenerator.view.MybatisJavaLineMarkerProvider.collectNavigationMarkers(MybatisJavaLineMarkerProvider.kt:25)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:39)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



```

**Comment by gejun123456** [comment]
谢谢反馈，我看下哈

**Comment by gejun123456** [comment]
这个影响使用吗，使用的插件版本和Intellij版本分别是多少哈

**Comment by gejun123456** [comment]
可以添加我微信 详细看一下
![default](https://user-images.githubusercontent.com/6340473/39742742-32bd39b4-52d1-11e8-9136-6aa755f25fbd.jpg)

**Comment by wzyjobs** [comment]
###  emmm 很影响 首先接口跳转图标没了 然后生成时就会报错** 主要是在赶项目进度 我先手写着
###插件版本是1.7.7
###IDEA版本是15.0.6

**Comment by gejun123456** [comment]
抱歉影响了你，我测测，怀疑可能是IDEA版本太低导致，可以下载一个1.7.0版本试试 
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=39656

**Comment by wzyjobs** [comment]
### 好的 我试试

**Comment by wzyjobs** [comment]
### 好的 等有时间了 再看看新版本

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.7.9.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/1983409/MyBatisCodeHelper-Pro-1.7.9.zip)

我打包了一个1.7.9版本哈，在本地可以用了，有时间可以试试哈
