### ISSUE TITLE
加载插件后，提示报错，我的版本是2017.1.5

### ISSUE THREAD

**Issue by chentong106140** [gejun123456/MyBatisCodeHelper-Pro#120]
class with name 'com.ccnode.codegenerator.view.MybatisGeneratorAction' cannot be loaded [Plugin: com.ccnode.codegenerator.MyBatisCodeHelperPro]
com.intellij.diagnostic.PluginException: class with name 'com.ccnode.codegenerator.view.MybatisGeneratorAction' cannot be loaded [Plugin: com.ccnode.codegenerator.MyBatisCodeHelperPro]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:485)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:473)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1246)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:34)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/mybatis/generator/exception/XMLParserException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.mybatis.generator.exception.XMLParserException PluginClassLoader[com.ccnode.codegenerator.MyBatisCodeHelperPro, 1.7.4]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

**Comment by gejun123456** [comment]
我看你这边使用的是1.7.4版本，可以下载1.8.0版本使用  https://plugins.jetbrains.com/plugin/download?rel=true&updateId=46084
