### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#14]
null
java.lang.NullPointerException
	at com.ccnode.codegenerator.util.PsiDocumentUtils.addImportToFileNoSave(PsiDocumentUtils.java:83)
	at com.ccnode.codegenerator.util.PsiDocumentUtils.addMethodToClass(PsiDocumentUtils.java:140)
	at com.ccnode.codegenerator.genmethodxml.GenMethodXmlInvoker.invoke(GenMethodXmlInvoker.java:284)
	at com.ccnode.codegenerator.view.MultipleMethodGenerateAction.actionPerformed(MultipleMethodGenerateAction.java:66)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)

**Comment by gejun123456** [comment]
fixed in version 1.6.6
