### ISSUE TITLE
用该插件连接mysql数据库时报错

### ISSUE THREAD

**Issue by githubzjl666** [gejun123456/MyBatisCodeHelper-Pro#162]
the exception is:java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:87)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:61)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:71)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)

**Comment by githubzjl666** [comment]
我使用navicat或者是web项目是可以连接到数据库的,使用的驱动mysql驱动是5.1.46.jar,我看博主插件使用的是8.0.11；而后我将web项目的jar包替换成8.0.11,依然提示“CLIENT_PLUGIN_AUTH is required”，博主下次发版是否可以换下驱动版本？

**Comment by gejun123456** [comment]
请问下mysql服务器版本是多少哈 
你是用添加数据库的方式来连的么
可以加我的qq：1098632410详聊下
