### ISSUE TITLE
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document! at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:344) at 

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#240]
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document! at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:344) at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:141) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87) at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192) at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:140) at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternal(XmlTagImpl.java:1119) at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternal(XmlTagImpl.java:1066) at com.intellij.psi.impl.source.tree.CompositePsiElement.addInnerBefore(CompositePsiElement.java:320) at com.intellij.psi.impl.source.tree.CompositePsiElement.addBefore(CompositePsiElement.java:156) at com.intellij.psi.impl.source.xml.XmlTagImpl.addSubTag(XmlTagImpl.java:1020) at com.ccnode.codegenerator.genmethodxml.GenMethodXmlInvoker$1.run(GenMethodXmlInvoker.java:198) at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:363) at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124) at com.intellij.openapi.application.RunResult.run(RunResult.java:35) at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264) at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057) at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263) at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:321) at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220) at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188) at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:323) at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262) at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244) at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126) at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:363) at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:355) at com.ccnode.codegenerator.genmethodxml.GenMethodXmlInvoker.invoke(GenMethodXmlInvoker.java:195) at com.ccnode.codegenerator.view.GenerateMethodXmlAction$invoke$1.run(GenerateMethodXmlAction.kt:55) at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762) at java.awt.EventQueue.access$500(EventQueue.java:98) at java.awt.EventQueue$3.run(EventQueue.java:715) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) at java.awt.EventQueue.dispatchEvent(EventQueue.java:732) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) the system os is:Windows 10 the intellij version is:IU-183.4284.148 the currentVersion are:2.0.2-SNAPSHOT userIp are:202.102.120.115 createTime is:2018 12 03 16:48:29

**Comment by gejun123456** [comment]
2.0.2 修复
