### ISSUE TITLE
不知道什么错 在报这个 =。=

### ISSUE THREAD

**Issue by lllvantis** [gejun123456/MyBatisCodeHelper-Pro#251]
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to Vantis Zhang
Subscription is active until March 12, 2019
For educational use only.
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

```
java.lang.RuntimeException: the fragment content is too deep, the current level is:501

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:26)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:56)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:56)

	at com.ccnode.codegenerator.util.MyPsiXmlUtils.collectOneSqlIdValue(MyPsiXmlUtils.kt:611)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.parseRefidFromXml(XmlTextContentCollector.java:205)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:92)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:56)

	at com.ccnode.codegenerator.xmlTextSqlInjector.XmlTextContentCollector.runThroghtTheTag(XmlTextContentCollector.java:56)

	at com.ccnode.codegenerator.xmlTextSqlInjector.MybatisMultiHostInjector.getLanguagesToInject(MybatisMultiHostInjector.java:50)

	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:77)

	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:410)

	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:57)

	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:340)

	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:167)

	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:137)

	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.hasInjections(InjectedLanguageUtil.java:632)

	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:50)

	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)

	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)

	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)

	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:50)

	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferencesImpl(XmlTagImpl.java:197)

	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:163)

	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:73)

	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)

	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:67)

	at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:119)

	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:254)

	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:229)

	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:503)

	at com.intellij.codeInsight.TargetElementUtil.findReference(TargetElementUtil.java:117)

	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:360)

	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:348)

	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:222)

	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:194)

	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:83)

	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)

	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)

	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)

	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)

	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)

	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)

	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)

	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)

	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)

	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)

	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)

	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)

	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)

	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by gejun123456** [comment]
带 mybatis的 if test where when 标签非常多的语句才会报这个错  一段sql 里面大于100个标签这种
影响是sql里面的字段无法做自动补全
我优化下
