### ISSUE TITLE
创建DataSources报错

### ISSUE THREAD

**Issue by rookiechw** [gejun123456/MyBatisCodeHelper-Pro#311]
是否可以自定义驱动jar包？
错误如下：
`the exception is:java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:108)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:87)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:61)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:71)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)`

**Comment by rookiechw** [comment]
可能是因为用了mycat的原因

**Comment by gejun123456** [comment]
嗯，直接用IDEA的数据库可以生成吧 https://raw.githubusercontent.com/gejun123456/MyBatisCodeHelper-Pro/master/screenshots/IntellijGenerateCrud.gif

**Comment by gejun123456** [comment]
有问题可以留言 先关闭了
