### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.java.ClassElement of type CLASS (class com.intellij.psi.impl.java.stubs.JavaStubElementTypes$1) at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96) at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101) at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253) at com.intellij.psi.impl.ResolveScopeManager.getElementResolveScope(ResolveScopeManager.java:49) at 

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#473]

**Comment by gejun123456** [comment]
用户使用2.7.2版本后问题消失，等待碰到的用户反馈
