### ISSUE TITLE
生成的批量insert的SQL，mybatis取出自增id报错

### ISSUE THREAD

**Issue by biubiubiu3971** [gejun123456/MyBatisCodeHelper-Pro#514]
mysql 版本 5.7
mybatis 版本 3.2.8

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [list, param1]

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy41.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy163.batchInsert(Unknown Source)

Caused by: org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [list, param1]
	at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:165)
	at org.apache.ibatis.reflection.wrapper.MapWrapper.getSetterType(MapWrapper.java:79)

**Comment by gejun123456** [comment]
插件啥版本，看下sql

**Comment by gejun123456** [comment]
用mybatis 新版本，老版本好像不支持

**Comment by gejun123456** [comment]
https://github.com/mybatis/mybatis-3/pull/547  mybatis 3.3.1 之后支持

**Comment by biubiubiu3971** [comment]
好吧~~
