### ISSUE TITLE
有时会报错 Threading assertion.  Under write: false;

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#55]
Threading assertion.  Under write: false; Thread.holdsLock(PsiLock.LOCK): false; wrapper: XmlTag:mapper; wrapper.isPhysical(): true; fileElement: Element(FILE); psiFile: XmlFile:NewFrozenLogMapper.xml; psiFile.getViewProvider(): SingleRootFileViewProvider
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.source.tree.CompositeElement.assertThreading(CompositeElement.java:122)
	at com.intellij.psi.impl.source.tree.CompositeElement.clearCaches(CompositeElement.java:109)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.clearCaches(XmlTagImpl.java:151)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addInternal(XmlTagImpl.java:1054)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addInnerBefore(CompositePsiElement.java:320)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.addBefore(CompositePsiElement.java:156)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.addSubTag(XmlTagImpl.java:996)

**Comment by gejun123456** [comment]
方法名生成sql时报错，在方法名上使用alt+enter可解决

**Comment by gejun123456** [comment]
1.7.3版本修复，待发布
