### ISSUE TITLE
 Inspection #MapperScan has no description

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#593]

**Comment by gejun123456** [comment]
[Plugin: com.ccnode.codegenerator.MyBatisCodeHelperPro] at com.intellij.codeInspection.ui.InspectionNodeInfo.(InspectionNodeInfo.java:74) at com.intellij.codeInspection.ui.InspectionResultsView.createBaseRightComponentFor(InspectionResultsView.java:465) at com.intellij.codeInspection.ui.InspectionResultsView.showInRightPanel(InspectionResultsView.java:393) at com.intellij.codeInspection.ui.InspectionResultsView.syncRightPanel(InspectionResultsView.java:310) at com.intellij.codeInspection.ui.InspectionTree$2.lambda$process$0(InspectionTree.java:117) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at
