### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by zhanghao1024** [gejun123456/MyBatisCodeHelper-Pro#597]
java.lang.AssertionError: valid to should not be null
	at com.ccnode.codegenerator.i.f.a.a(a.java:261)
	at com.ccnode.codegenerator.i.l.a(l.java:24)
	at com.ccnode.codegenerator.O.a.b.e(b.java:69)
	at com.ccnode.codegenerator.w.b.lambda$runActivity$0(b.java:40)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by gejun123456** [comment]
重新激活下看看

**Comment by gejun123456** [comment]
把用户目录 .config文件删掉再试下就行罗
