### ISSUE TITLE
idea 2020.2报错了

### ISSUE THREAD

**Issue by zhidongluo** [gejun123456/MyBatisCodeHelper-Pro#619]
java.lang.AssertionError: valid to should not be null
	at com.ccnode.codegenerator.a.a.d.a(d.java:261)
	at com.ccnode.codegenerator.a.g.a(g.java:24)
	at com.ccnode.codegenerator.ad.a.a.a(a.java:69)
	at com.ccnode.codegenerator.f.c.lambda$runActivity$0(c.java:42)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by gejun123456** [comment]
把用户目录的 .config文件夹删下就好了
