### ISSUE TITLE
Thread limit exceeded replacing blocked worker

### ISSUE THREAD

**Issue by zzqo** [gejun123456/MyBatisCodeHelper-Pro#827]
### 重现步骤(Repeat steps)
- 从一个mapper.xml文件切换到另一个mapper.xml文件

### 当前使用版本(Current Version)

IntelliJ IDEA `2022.3` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.3`

### Exception

null

```
java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:1819)
	at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3446)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3432)
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.editorconfig.configmanagement.extended.EditorConfigCodeStyleSettingsModifier.runWithTimeout(EditorConfigCodeStyleSettingsModifier.java:124)
	at org.editorconfig.configmanagement.extended.EditorConfigCodeStyleSettingsModifier.modifySettings(EditorConfigCodeStyleSettingsModifier.java:75)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.computeSettings(CodeStyleCachedValueProvider.java:203)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.lambda$start$3(CodeStyleCachedValueProvider.java:141)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:58)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.start(CodeStyleCachedValueProvider.java:141)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.getCurrResult(CodeStyleCachedValueProvider.java:245)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider.compute(CodeStyleCachedValueProvider.java:77)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider.tryGetSettings(CodeStyleCachedValueProvider.java:61)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachingServiceImpl.tryGetSettings(CodeStyleCachingServiceImpl.java:52)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:97)
	at com.intellij.application.options.CodeStyle.getCustomSettings(CodeStyle.java:167)
	at com.intellij.psi.codeStyle.JavaCodeStyleSettings.getInstance(JavaCodeStyleSettings.java:395)
	at com.intellij.codeInsight.ExternalAnnotationsManagerImpl.chooseAnnotationsPlace(ExternalAnnotationsManagerImpl.java:767)
	at com.intellij.codeInsight.ExternalAnnotationsManagerImpl.chooseAnnotationsPlaceNoUi(ExternalAnnotationsManagerImpl.java:744)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.choosePlace(AddAnnotationPsiFix.java:256)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.<init>(AddAnnotationPsiFix.java:63)
	at com.intellij.codeInsight.intention.AddAnnotationFix.<init>(AddAnnotationFix.java:42)
	at de.plushnikov.intellij.plugin.quickfix.PsiQuickFixFactory.createAddAnnotationQuickFix(PsiQuickFixFactory.java:21)
	at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.lambda$validateCallSuperParamExtern$2(EqualsAndHashCodeProcessor.java:93)
	at com.intellij.util.containers.ContainerUtil.map2Array(ContainerUtil.java:826)
	at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.validateCallSuperParam(EqualsAndHashCodeProcessor.java:108)
	at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.validateCallSuperParamExtern(EqualsAndHashCodeProcessor.java:92)
	at de.plushnikov.intellij.plugin.processor.clazz.DataProcessor.validate(DataProcessor.java:57)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getPsis(LombokAugmentProvider.java:118)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:111)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$3(PsiAugmentProvider.java:134)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:257)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:133)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.calcMethods(ClassInnerStuffCache.java:143)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$1(ClassInnerStuffCache.java:51)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:51)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:281)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberType.getMembers(PsiClassImplUtil.java:173)
	at one.util.streamex.AbstractStreamEx.lambda$flatArray$17(AbstractStreamEx.java:683)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at one.util.streamex.StreamEx.toArray(StreamEx.java:871)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.lambda$new$3(PsiClassImplUtil.java:351)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.getAllMembers(PsiClassImplUtil.java:385)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:165)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllMethods(PsiClassImplUtil.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.getAllMethods(PsiClassImpl.java:340)
	at com.intellij.psi.util.PropertyUtilBase.getReadableProperties(PropertyUtilBase.java:189)
	at com.ccnode.codegenerator.v.Z.a(Z.java:491)
	at com.ccnode.codegenerator.v.Z.a(Z.java:457)
	at com.ccnode.codegenerator.L.a.compute(a.java:41)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.ccnode.codegenerator.L.b.a(b.java:39)
	at com.ccnode.codegenerator.v.Z.a(Z.java:159)
	at com.ccnode.codegenerator.u.b.a(b.java:82)
	at com.ccnode.codegenerator.u.e.a(e.java:15)
	at com.ccnode.codegenerator.u.d.b(d.java:76)
	at com.ccnode.codegenerator.u.c.a(c.java:58)
	at com.ccnode.codegenerator.u.c.resolve(c.java:55)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$5(ResolveCache.java:272)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:215)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:272)
	at com.ccnode.codegenerator.u.d.resolve(d.java:47)
	at com.ccnode.codegenerator.o.b.b.a(b.java:79)
	at a.a.a.e.a(e.java:21)
	at a.a.a.e.accept(e.java:25)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$9(InspectionRunner.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:332)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:338)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:301)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:301)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:284)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:360)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:300)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:275)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:116)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspectInjectedPsi$16(InspectionRunner.java:408)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by gejun123456** [comment]
可以看下xml吗 第一次见这个错
