### ISSUE TITLE
2022.3 频繁报错

### ISSUE THREAD

**Issue by leleplus** [gejun123456/MyBatisCodeHelper-Pro#830]
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2022.3` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.3`

### Exception

null

```
java.lang.Throwable: Assertion failed: com.intellij.psi.impl.source.tree.java.PsiBinaryExpressionImpl
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:254)
	at com.intellij.psi.ElementManipulators.getNotNullManipulator(ElementManipulators.java:38)
	at com.intellij.psi.ElementManipulators.getOffsetInElement(ElementManipulators.java:31)
	at com.ccnode.codegenerator.T.b.a(b.java:152)
	at com.ccnode.codegenerator.T.b.a(b.java:137)
	at com.ccnode.codegenerator.T.b.getCustomComponents(b.java:83)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.computeCustomBeans(AbstractSimpleLocalModel.java:90)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.lambda$getLocalBeans$1(AbstractSimpleLocalModel.java:76)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.getLocalBeans(AbstractSimpleLocalModel.java:84)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.doProcessLocalBeansByClass(CacheableCommonSpringModel.java:67)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansByClassCachingProcessor.doProcessBeans(CacheableCommonSpringModel.java:210)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansByClassCachingProcessor.doProcessBeans(CacheableCommonSpringModel.java:205)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansCachingProcessor.findPointers(CacheableCommonSpringModel.java:181)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:37)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:33)
	at com.intellij.spring.contexts.model.SpringSizeLimitedCache.get(SpringSizeLimitedCache.java:41)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:64)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.processLocalBeansByClass(CacheableCommonSpringModel.java:58)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.processByClass(CacheableCommonSpringModel.java:48)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.lambda$processByClass$0(AbstractProcessableModel.java:26)
	at com.intellij.spring.contexts.model.visitors.CommonSpringModelVisitorContext.visit(CommonSpringModelVisitorContext.java:30)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:50)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:59)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelated(SpringModelVisitors.java:51)
	at com.intellij.spring.contexts.model.visitors.SpringModelVisitors.visitRelatedModels(SpringModelVisitors.java:30)
	at com.intellij.spring.contexts.model.AbstractProcessableModel.processByClass(AbstractProcessableModel.java:26)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:33)
	at com.intellij.spring.java.SpringJavaClassInfo.lambda$new$0(SpringJavaClassInfo.java:76)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.spring.java.SpringJavaClassInfo.resolve(SpringJavaClassInfo.java:143)
	at com.intellij.spring.gutter.SpringBeanAnnotator.annotateMethod(SpringBeanAnnotator.java:198)
	at com.intellij.spring.gutter.SpringAnnotatorBase.annotateMethod(SpringAnnotatorBase.java:51)
	at com.intellij.spring.gutter.SpringAnnotatorBase.collectNavigationMarkers(SpringAnnotatorBase.java:35)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:35)
	at com.intellij.spring.gutter.SpringAnnotatorBase.collectNavigationMarkers(SpringAnnotatorBase.java:69)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:27)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:224)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by gejun123456** [comment]
应该是mapperScan的配置里面 字符串用了 加号比如 com.xx+mapper 这种导致的，改成不带+号就好了，下个版本修复

**Comment by leleplus** [comment]
确定没有用+,基本上都是数组多个值，然后通配符*或者**

**Comment by gejun123456** [comment]
那不应该 看下mapperscan配置 我试试

**Comment by gejun123456** [comment]
我先试一下

**Comment by gejun123456** [comment]
可以加入 
![image](https://user-images.githubusercontent.com/6340473/207502390-4a119454-10e2-46e1-b42a-6e496f4bceae.png)
看看
qq群文件有修复的版本

**Comment by gejun123456** [comment]
已修复
