### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by witt-bit** [gejun123456/MyBatisCodeHelper-Pro#840]
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2022.3.1` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.5`

### Exception

provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@1a62ff55

```
java.lang.RuntimeException: java.io.EOFException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:319)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:953)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:811)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.readContent(PersistentFSImpl.java:285)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:586)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:126)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:118)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:575)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:549)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.loadText(FileDocumentManagerBase.java:90)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerBase.getDocument(FileDocumentManagerBase.java:47)
	at com.intellij.psi.AbstractFileViewProvider.getDocument(AbstractFileViewProvider.java:178)
	at com.intellij.psi.AbstractFileViewProvider$VirtualFileContent.getText(AbstractFileViewProvider.java:466)
	at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:158)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:210)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.psi.impl.source.PsiFieldImpl.getNode(PsiFieldImpl.java:88)
	at com.intellij.psi.impl.source.PsiFieldImpl.getDocComment(PsiFieldImpl.java:310)
	at com.intellij.psi.impl.PsiImplUtil.isDeprecatedByDocTag(PsiImplUtil.java:452)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderInfo.isDeprecated(BuilderInfo.java:110)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderInfo.fromPsiField(BuilderInfo.java:78)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.createBuilderInfos(BuilderHandler.java:476)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.createBuilderDefaultProviderMethodsIfNecessary(BuilderHandler.java:357)
	at de.plushnikov.intellij.plugin.processor.method.BuilderMethodProcessor.processIntern(BuilderMethodProcessor.java:56)
	at de.plushnikov.intellij.plugin.processor.method.AbstractMethodProcessor.process(AbstractMethodProcessor.java:50)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getPsis(LombokAugmentProvider.java:118)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:111)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$3(PsiAugmentProvider.java:134)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:257)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:133)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.calcMethods(ClassInnerStuffCache.java:143)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$1(ClassInnerStuffCache.java:51)
	at com.intellij.psi.util.CachedValuesManager.lambda$getProjectPsiDependentCache$0(CachedValuesManager.java:134)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getProjectPsiDependentCache(CachedValuesManager.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:51)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:281)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberType.getMembers(PsiClassImplUtil.java:173)
	at one.util.streamex.AbstractStreamEx.lambda$flatArray$17(AbstractStreamEx.java:683)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at one.util.streamex.StreamEx.toArray(StreamEx.java:871)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.lambda$new$3(PsiClassImplUtil.java:351)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MemberCache.getAllMembers(PsiClassImplUtil.java:385)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:165)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllMethods(PsiClassImplUtil.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.getAllMethods(PsiClassImpl.java:340)
	at com.ccnode.codegenerator.E.aF.a(aF.java:60)
	at com.ccnode.codegenerator.E.aF.f(aF.java:83)
	at com.ccnode.codegenerator.E.aF.b(aF.java:36)
	at com.ccnode.codegenerator.w.p.a(p.java:43)
	at com.ccnode.codegenerator.w.o.d(o.java:54)
	at com.ccnode.codegenerator.w.o.b(o.java:36)
	at com.ccnode.codegenerator.w.v.resolve(v.java:45)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:118)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:35)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:968)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:85)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:176)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:203)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:175)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:964)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:289)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:561)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:540)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:411)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:482)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$10(PsiSearchHelperImpl.java:481)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.EOFException
	at com.intellij.util.io.storage.RefCountingContentStorage$CustomInflaterInputStream.fill(RefCountingContentStorage.java:91)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at com.intellij.openapi.util.io.StreamUtil.copy(StreamUtil.java:33)
	at com.intellij.util.io.storage.RefCountingContentStorage.internalReadStream(RefCountingContentStorage.java:76)
	at com.intellij.util.io.storage.RefCountingContentStorage.readStream(RefCountingContentStorage.java:60)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSContentAccessor.readContentDirectly(PersistentFSContentAccessor.java:58)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSContentAccessor.readContent(PersistentFSContentAccessor.java:47)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:805)
	... 117 more
```

**Comment by gejun123456** [comment]
看着是调用idea内部的api报错了

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/210473974-2beb0bd7-1a6b-4d3f-8d77-ef606b647ab2.png)
怀疑是lombok插件出问题了，禁用掉lombok插件试试
