### ISSUE TITLE
提示null

### ISSUE THREAD

**Issue by abc45628** [gejun123456/MyBatisCodeHelper-Pro#849]
开着xml，然后rebase一下git，突然就报错了
--------------------------
                        
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2022.3.1` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.5`

### Exception

null

```
java.lang.AssertionError: Invalid retrieved beaninterface com.intellij.spring.aop.model.xml.TxAnnotationDriven @-2144459409
class=class com.intellij.util.xml.impl.CollectionElementInvocationHandler
xml=XmlTag:tx:annotation-driven; element changed: interface com.intellij.spring.aop.model.xml.TxAnnotationDriven @-2144459409&handler={}&cd=CollectionChildDescription:Spring TX namespace key : annotation-driven&ps=com.intellij.util.xml.stubs.StubParentStrategy@1d68df51!=interface com.intellij.spring.aop.model.xml.TxAnnotationDriven @-2144459409&handler={}&cd=CollectionChildDescription:Spring TX namespace key : annotation-driven&ps=com.intellij.util.xml.stubs.StubParentStrategy@5b9e767
	at com.intellij.util.xml.impl.DomImplUtil.assertValidity(DomImplUtil.java:48)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.getSpringBean(DomSpringBeanPointerImpl.java:61)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.lambda$getBeanClass$0(DomSpringBeanPointerImpl.java:89)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.getBeanClass(DomSpringBeanPointerImpl.java:93)
	at com.ccnode.codegenerator.ac.j.a(j.java:77)
	at com.ccnode.codegenerator.ac.j.a(j.java:58)
	at com.ccnode.codegenerator.ac.i.a(i.java:31)
	at com.ccnode.codegenerator.ac.e.a(e.java:62)
	at com.ccnode.codegenerator.ac.b.resolve(b.java:47)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.hasBadResolve(XmlHighlightVisitor.java:531)
	at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.hasBadResolve(DomHighlightingHelperImpl.java:163)
	at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.checkResolveProblems(DomHighlightingHelperImpl.java:105)
	at com.intellij.util.xml.highlighting.BasicDomElementsInspection.checkDomElement(BasicDomElementsInspection.java:47)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:82)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:66)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:82)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:66)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFileElement(DomElementsInspection.java:70)
	at com.intellij.util.xml.highlighting.DomElementAnnotationsManagerImpl.checkFileElement(DomElementAnnotationsManagerImpl.java:205)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkDomFile(DomElementsInspection.java:143)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFile(DomElementsInspection.java:117)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:141)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:57)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$9(InspectionRunner.java:312)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:332)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:338)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:301)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:301)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:284)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:352)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:300)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:275)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:370)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:346)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by gejun123456** [comment]
https://share.weiyun.com/YcXuRnGj 可以试试这个版本 修了下

**Comment by gejun123456** [comment]
已修复
