### ISSUE TITLE
Error during processing of: FileDetailMapper.xml

### ISSUE THREAD

**Issue by sumulige** [gejun123456/MyBatisCodeHelper-Pro#870]
> <!--https://github.com/gejun123456/MyBatisCodeHelper-Pro/issues/new paste current content to github issues--
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2021.3.2` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.7`

### Exception

Error during processing of: FileDetailMapper.xml

```
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:185)
	at com.intellij.util.io.CompressedAppendableFile.access$100(CompressedAppendableFile.java:30)
	at com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.get(CompressedAppendableFile.java:464)
	at com.intellij.util.io.CompressedAppendableFile$SegmentedChunkInputStream.read(CompressedAppendableFile.java:519)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at com.intellij.util.io.PersistentHashMapValueStorage$ReaderOverCompressedFile.get(PersistentHashMapValueStorage.java:772)
	at com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:542)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:604)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:545)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:178)
	at com.intellij.database.model.ModelEntityStoragePersistentBackend.getDataObject(ModelEntityStoragePersistentBackend.kt:147)
	at com.intellij.database.model.ModelEntityStorage.getDataObject(ModelEntityStorage.java:43)
	at com.intellij.database.model.BaseModel$BaseElement.loadEntity(BaseModel.java:562)
	at com.intellij.database.model.BaseModel$BaseElement.getData(BaseModel.java:551)
	at com.intellij.database.model.BaseModel$BaseElement.getDelegate(BaseModel.java:626)
	at com.intellij.database.dialects.mysql.model.MysqlImplModel$Schema.isCurrent(MysqlImplModel.java:6539)
	at com.intellij.database.model.basic.BasicModel.getCurrentRootNamespace(BasicModel.java:63)
	at com.intellij.sql.dialects.SqlLanguageDialectEx.getDefaultTopNamespace(SqlLanguageDialectEx.java:699)
	at com.intellij.sql.dialects.SqlLanguageDialectEx.getDefaultNamespace(SqlLanguageDialectEx.java:708)
	at com.intellij.sql.dialects.mysql.MysqlDialectBase.getBaseImports(MysqlDialectBase.java:144)
	at com.intellij.sql.dialects.SqlLanguageDialectEx.getDefaultImports(SqlLanguageDialectEx.java:272)
	at com.intellij.sql.dialects.SqlImportUtil.createDefaultScopePattern(SqlImportUtil.java:66)
	at com.intellij.sql.dialects.SqlImportBuilder.lambda$getDefaultInitialPattern$4(SqlImportBuilder.java:118)
	at com.intellij.util.containers.JBIterator$MapOp.apply(JBIterator.java:299)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at com.intellij.util.containers.JBIterable$FlattenFun$FlattenIt.nextImpl(JBIterable.java:469)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at com.intellij.database.util.TreePatternUtils$GroupedGroupFactory.mergeNodes(TreePatternUtils.java:315)
	at com.intellij.database.util.TreePatternUtils$GroupedGroupFactory.mergeRoots(TreePatternUtils.java:355)
	at com.intellij.database.util.TreePatternUtils$GroupedGroupFactory.merge(TreePatternUtils.java:349)
	at com.intellij.database.util.TreePatternUtils.union(TreePatternUtils.java:486)
	at com.intellij.sql.dialects.SqlImportBuilder.getDefaultInitialPattern(SqlImportBuilder.java:117)
	at com.intellij.sql.dialects.SqlImportBuilder.calcInitialImportState(SqlImportBuilder.java:85)
	at com.intellij.sql.dialects.SqlImportBuilder.buildImports(SqlImportBuilder.java:49)
	at com.intellij.sql.dialects.SqlDialectImplUtilCore.calcImports(SqlDialectImplUtilCore.java:225)
	at com.intellij.sql.dialects.SqlDialectImplUtilCore.lambda$buildImports$0(SqlDialectImplUtilCore.java:199)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.sql.dialects.SqlDialectImplUtilCore.buildImports(SqlDialectImplUtilCore.java:197)
	at com.intellij.sql.dialects.SqlDialectImplUtilCore.getImportCheckerAt(SqlDialectImplUtilCore.java:192)
	at com.intellij.sql.psi.impl.SqlFileImpl.processDeclarations(SqlFileImpl.java:510)
	at com.intellij.sql.psi.SqlElement.processDeclarations(SqlElement.java:32)
	at com.intellij.sql.psi.impl.SqlImplUtil.treeWalkUp(SqlImplUtil.java:1501)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.processUnqualifiedResolveVariants(SqlReferenceImpl.java:610)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.processResolveVariants(SqlReferenceImpl.java:444)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.resolveInner(SqlReferenceImpl.java:412)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.lambda$static$0(SqlReferenceImpl.java:73)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.multiResolve(SqlReferenceImpl.java:172)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.resolveSingle(SqlReferenceImpl.java:177)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.getSqlTypeInner(SqlReferenceImpl.java:137)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.lambda$static$1(SqlReferenceImpl.java:82)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.getSqlType(SqlReferenceImpl.java:110)
	at com.intellij.sql.psi.impl.SqlReferenceExpressionImpl.getSqlType(SqlReferenceExpressionImpl.java:62)
	at com.intellij.sql.psi.impl.SqlImplUtil.getTypeLateralAware(SqlImplUtil.java:937)
	at com.intellij.sql.psi.impl.SqlImplUtil.processFromReferences(SqlImplUtil.java:916)
	at com.intellij.sql.psi.impl.SqlFromClauseImpl.processDeclarations(SqlFromClauseImpl.java:47)
	at com.intellij.sql.psi.impl.SqlTableExpressionImpl.processDeclarations(SqlTableExpressionImpl.java:33)
	at com.intellij.sql.psi.impl.SqlQueryExpressionImpl.processDeclarations(SqlQueryExpressionImpl.java:49)
	at com.intellij.sql.psi.SqlElement.processDeclarations(SqlElement.java:32)
	at com.intellij.sql.psi.impl.SqlImplUtil.treeWalkUp(SqlImplUtil.java:1501)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.processUnqualifiedResolveVariants(SqlReferenceImpl.java:610)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.processResolveVariants(SqlReferenceImpl.java:444)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.resolveInner(SqlReferenceImpl.java:412)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.lambda$static$0(SqlReferenceImpl.java:73)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.multiResolve(SqlReferenceImpl.java:172)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.resolveSingle(SqlReferenceImpl.java:177)
	at com.intellij.sql.psi.impl.SqlReferenceImpl.resolve(SqlReferenceImpl.java:198)
	at com.intellij.sql.psi.impl.SqlReferenceExpressionImpl.resolve(SqlReferenceExpressionImpl.java:216)
	at com.ccnode.codegenerator.Z.a.j.isReferenceTo(j.java:117)
	at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processReference(MethodTextOccurrenceProcessor.java:49)
	at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processTextOccurrence(MethodTextOccurrenceProcessor.java:33)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:958)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:88)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:179)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:206)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:954)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:279)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:270)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$17(PsiSearchHelperImpl.java:915)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$10(PsiSearchHelperImpl.java:551)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:530)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:399)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:472)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:471)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at net.jpountz.util.SafeUtils.checkRange(SafeUtils.java:26)
	at net.jpountz.util.UnsafeUtils.checkRange(UnsafeUtils.java:58)
	at net.jpountz.lz4.LZ4JavaUnsafeFastDecompressor.decompress(LZ4JavaUnsafeFastDecompressor.java:24)
	at net.jpountz.lz4.LZ4FastDecompressor.decompress(LZ4FastDecompressor.java:109)
	at com.intellij.util.CompressionUtil.readCompressedWithoutOriginalBufferLength(CompressionUtil.java:93)
	at com.intellij.util.io.CompressedAppendableFile.decompress(CompressedAppendableFile.java:353)
	at com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:173)
	... 155 more
```

**Comment by gejun123456** [comment]
any error log?  idea.log
