### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by forever-Nana** [gejun123456/MyBatisCodeHelper-Pro#886]
### 当前使用版本(Current Version)

IntelliJ IDEA `2023.1.1` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.1.6`

### Exception

null

```
com.intellij.diagnostic.PluginException: Cannot load class com.ccnode.codegenerator.D.l.p (
  error: com/intellij/spring/model/highlighting/jam/AbstractSpringJavaConfigInspection,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=MyBatisCodeHelperPro, id=com.ccnode.codegenerator.MyBatisCodeHelperPro, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/MyBatisCodeHelper-Pro, version=3.1.6, package=null, isBundled=false), packagePrefix=null, instanceId=400, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:325)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:172)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1629)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:28)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:224)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:84)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getGroupDisplayName(InspectionToolWrapper.java:152)
	at com.intellij.ide.ui.ToolOptionDescription.<init>(ToolOptionDescription.java:20)
	at com.intellij.ide.ui.InspectionsTopHitProvider.getOptions(InspectionsTopHitProvider.java:31)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:60)
	at com.intellij.ide.ui.TopHitCache$getCachedOptions$1.invoke(TopHitCache.kt:47)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions$lambda$0(TopHitCache.kt:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.ide.ui.TopHitCache.getCachedOptions(TopHitCache.kt:47)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.execute(OptionsTopHitProvider.kt:155)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity$execute$1.invokeSuspend(OptionsTopHitProvider.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NoClassDefFoundError: com/intellij/spring/model/highlighting/jam/AbstractSpringJavaConfigInspection
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:112)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:233)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:183)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:320)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.intellij.spring.model.highlighting.jam.AbstractSpringJavaConfigInspection PluginClassLoader(plugin=PluginDescriptor(name=MyBatisCodeHelperPro, id=com.ccnode.codegenerator.MyBatisCodeHelperPro, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/MyBatisCodeHelper-Pro, version=3.1.6, package=null, isBundled=false), packagePrefix=null, instanceId=400, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 32 more
```

**Comment by gejun123456** [comment]
升级一下插件到3.1.9 看看
