### ISSUE TITLE
MyBatisCodeHelperException

### ISSUE THREAD

**Issue by ByeJuly** [gejun123456/MyBatisCodeHelper-Pro#944]
This is the MyBatisCodeHelperException,Message is ,Sorry,No Have Picture or Gif ->   

 
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2023.2.1` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.2.3`

### Exception

*** exception class was changed or removed

```
Error during processing of: CategoryMapper.xml
   
   java.lang.AssertionError: Invalid retrieved beaninterface com.intellij.spring.model.xml.beans.SpringBean @3019698
class=class com.intellij.util.xml.impl.CollectionElementInvocationHandler
xml=XmlTag:bean; element changed: interface com.intellij.spring.model.xml.beans.SpringBean @3019698&handler={}&cd=CollectionChildDescription:Spring beans namespace key : bean&ps=com.intellij.util.xml.stubs.StubParentStrategy@47f5a20a!=interface com.intellij.spring.model.xml.beans.SpringBean @3019698&handler={}&cd=CollectionChildDescription:Spring beans namespace key : bean&ps=com.intellij.util.xml.stubs.StubParentStrategy@2323cb33
	at com.intellij.util.xml.impl.DomImplUtil.assertValidity(DomImplUtil.java:48)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.getSpringBean(DomSpringBeanPointerImpl.java:61)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.getSpringBean(DomSpringBeanPointerImpl.java:26)
	at com.intellij.spring.model.xml.beans.impl.SpringBeanImpl.getBeanClass(SpringBeanImpl.java:163)
	at com.intellij.spring.model.xml.AbstractDomSpringBean.getBeanType(AbstractDomSpringBean.java:56)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.lambda$getBeanClass$0(DomSpringBeanPointerImpl.java:89)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.spring.model.xml.DomSpringBeanPointerImpl.getBeanClass(DomSpringBeanPointerImpl.java:93)
	at com.ccnode.codegenerator.f.o.a(o.java:77)
	at com.ccnode.codegenerator.f.o.a(o.java:59)
	at com.ccnode.codegenerator.f.n.a(n.java:31)
	at com.ccnode.codegenerator.f.g.a(g.java:62)
	at com.ccnode.codegenerator.dom.a.m.a(m.java:33)
	at com.ccnode.codegenerator.dom.a.m.fromString(m.java:24)
	at com.intellij.util.xml.impl.GetInvocation.getValueInner(GetInvocation.java:96)
	at com.intellij.util.xml.impl.GetInvocation.getOrCalcValue(GetInvocation.java:71)
	at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:59)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:655)
	at com.intellij.util.xml.GenericAttributeValue$$EnhancerByJetBrainsMainCglib$$f4a47684.getValue(<generated>)
	at com.ccnode.codegenerator.dom.d.a(d.java:52)
	at com.ccnode.codegenerator.L.p.a(p.java:42)
	at com.ccnode.codegenerator.L.o.d(o.java:54)
	at com.ccnode.codegenerator.L.o.b(o.java:36)
	at com.ccnode.codegenerator.L.i.resolve(i.java:45)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:118)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:35)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:968)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:85)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:176)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:203)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:175)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:964)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:289)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:561)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:540)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:411)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:482)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$10(PsiSearchHelperImpl.java:481)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:142)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:110)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:88)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by gejun123456** [comment]
mybatis的spring是怎么配置的 是使用xml配置的吗
