### ISSUE TITLE
随机触发空指针异常

### ISSUE THREAD

**Issue by farawaysummer** [gejun123456/MyBatisCodeHelper-Pro#970]
编辑kotlin类（与数据库操作无关）时随机报错

                        
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

### 当前使用版本(Current Version)

IntelliJ IDEA `2023.3.2` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.2.8`

### Exception

null

```
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1836.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:672)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:367)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:324)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:297)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:140)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:246)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:126)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4652)
	at com.ccnode.codegenerator.w.b.a(b.java:180)
	at com.ccnode.codegenerator.w.b.a(b.java:189)
	at com.ccnode.codegenerator.w.b.a(b.java:149)
	at com.ccnode.codegenerator.w.b.getCustomComponents(b.java:87)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.computeCustomBeans(AbstractSimpleLocalModel.java:90)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.lambda$getLocalBeans$1(AbstractSimpleLocalModel.java:76)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.spring.contexts.model.AbstractSimpleLocalModel$CustomDiscoveredBeansModel.getLocalBeans(AbstractSimpleLocalModel.java:84)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.doProcessLocalBeansByClass(CacheableCommonSpringModel.java:67)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansByClassCachingProcessor.doProcessBeans(CacheableCommonSpringModel.java:210)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansByClassCachingProcessor.doProcessBeans(CacheableCommonSpringModel.java:205)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel$LocalBeansCachingProcessor.findPointers(CacheableCommonSpringModel.java:181)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:37)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:33)
	at com.intellij.spring.contexts.model.SpringSizeLimitedCache.get(SpringSizeLimitedCache.java:51)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:64)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.processLocalBeansByClass(CacheableCommonSpringModel.java:58)
	at com.intellij.spring.contexts.model.CacheableCommonSpringModel.traverseByClass(CacheableCommonSpringModel.java:48)
	at com.intellij.spring.model.utils.SpringModelSearchers.lambda$findBeans$0(SpringModelSearchers.java:34)
	at com.intellij.spring.contexts.model.ModelTraverse.visitModel(ModelTraverse.kt:76)
	at com.intellij.spring.contexts.model.ModelTraverse.visitRelated(ModelTraverse.kt:55)
	at com.intellij.spring.contexts.model.ModelTraverse.visitRelated(ModelTraverse.kt:60)
	at com.intellij.spring.contexts.model.ModelTraverse.visitRelated(ModelTraverse.kt:60)
	at com.intellij.spring.contexts.model.ModelTraverse.traverseModel(ModelTraverse.kt:47)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:34)
	at com.intellij.spring.java.SpringJavaClassInfo$MappedBeanInfo.lambda$new$1(SpringJavaClassInfo.java:199)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.spring.java.SpringJavaClassInfo$MappedBeanInfo.isStereotypeJavaBean(SpringJavaClassInfo.java:246)
	at com.intellij.spring.model.highlighting.autowire.SpringUastAutowiredMembersChecker.checkClass(SpringUastAutowiredMembersChecker.java:51)
	at com.intellij.spring.model.highlighting.autowire.SpringAutowiringInspection$1.visitClass(SpringAutowiringInspection.java:56)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:168)
	at com.intellij.uast.UastHintedVisitorAdapter.visitElement(UastHintedVisitorAdapter.kt:28)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:52)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:367)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:379)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:385)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:158)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:150)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:325)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:325)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:292)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:278)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	... 5 more
```

**Comment by gejun123456** [comment]
可以看下报错对应的kotlin类吗

**Comment by farawaysummer** [comment]
kotlin类没有什么特别之处，是springboot的入口main方法类

**Comment by gejun123456** [comment]
群文件已修复 估计这周发布
