### ISSUE TITLE
Start IDE in IntelliJ IDEA 2024.1 Beta, then error occured.

### ISSUE THREAD

**Issue by Luxusio** [gejun123456/MyBatisCodeHelper-Pro#979]
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- please describe what you were doing when this exception occurred

Start IDE in IntelliJ IDEA 2024.1 Beta

### 当前使用版本(Current Version)

IntelliJ IDEA `2024.1 Beta` • Notes plugin `com.ccnode.codegenerator.MyBatisCodeHelperPro 3.2.9`

### Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.ccnode.codegenerator.U.k' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.ccnode.codegenerator.MyBatisCodeHelperPro]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by gejun123456** [comment]
https://plugins.jetbrains.com/plugin/9837-mybatiscodehelperpro/edit/versions/eap/506441 可以试试这个版本

**Comment by gejun123456** [comment]
will release in two days. thanks for reporting.
